esphome:
  name: meat-thermometer
  friendly_name: Meat Thermometer

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CHANGE_THIS"

ota:
  - platform: esphome
    password: "CHANGE_THIS"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Meat Thermometer Fallback Hotspot"
    password: "CHANGE_THIS"

captive_portal:

sensor:
  - platform: ntc
    sensor: resistance_ntc
    calibration:
      - 25.704kOhm -> 16째C
      - 23.364kOhm -> 23째C
      - 12.221kOhm -> 57째C
    name: "Probe Temperature"
    unit_of_measurement: "째C"
    accuracy_decimals: 1

  - platform: resistance
    id: resistance_ntc
    sensor: a0_voltage
    configuration: DOWNSTREAM
    resistor: 100kOhm
    name: "Probe Resistance"

  - platform: adc
    id: a0_voltage
    pin: A0
    update_interval: 5s
    name: "A0 Voltage"
